logging:
  level:
    com:
      prpa: ${LOG_APPLICATION:DEBUG}
    org:
      hibernate: ${LOG_HIBERNATE:INFO}
      springframework:
        root: ${LOG_ROOT:INFO}
        web: ${LOG_WEB:INFO}
        security: ${LOG_SEC:INFO}
        transaction:
          interceptor: ${LOG_TRANSACTION:INFO}
        orm:
          jpa: ${LOG_JPA:INFO}

application:
  aop:
    logging: true

spring:
  datasource:
#    url: jdbc:h2:file:./dev
    url: jdbc:h2:mem:dev
    username: dev
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html